// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c3a7af70a9dbc18e77b221de4d6dfddb3a27ede4/electron-json-storage/electron-json-storage.d.ts
declare module "electron-json-storage" {
	export function get(key: string, callback: (error: any, data: Object) => void): void;
	export function set(key: string, json: Object, callback: (error: any) => void): void;
	export function has(key: string, callback: (error: any, hasKey: boolean) => void): void;
	export function keys(callback: (error: any, keys: string[]) => void): void;
	export function remove(key: string, callback: (error: any) => void): void;
	export function clear(callback: (error: any) => void): void;
}
